[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    storage.path /var/log/fluent-bit/buffer
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 50M

[INPUT]
    Name         tail
    Path         /var/log/nginx/access.log
    Tag          nginx.access
    Parser       nginx
    storage.type filesystem

[INPUT]
    Name         systemd
    Tag          systemd.logs
    Systemd_Filter _SYSTEMD_UNIT=sshd.service

[FILTER]
    Name         modify
    Match        *
    Add          hostname ${HOSTNAME}
    Add          env production

[OUTPUT]
    Name         loki
    Match        *
    Host         loki-internal.ematiq.com
    Port         3100
    Labels       job=ec2-logs, instance=${HOSTNAME}
    Remove_Keys  hostname
    Line_Format  json